task: classifier

dataloader:
  dataset: vanilla
  batch_size: 16
  preprocess: null
  transform:
    train:
      - function: Resize
        params:
          size: 256
      - function: RandomHorizontalFlip
      - function: ToPILImage
        params:
          mode: RGB
      - function: CenterCrop
        params:
          size: 224
      - function: ToTensor
      - function: Normalize
        params:
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
    valid:
      - function: Resize
        params:
          size: 256
      - function: RandomHorizontalFlip
      - function: ToPILImage
        params:
          mode: RGB
      - function: CenterCrop
        params:
          size: 224
      - function: ToTensor
      - function: Normalize
        params:
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
    test:
      - function: Resize
        params:
          size: 256
      - function: RandomHorizontalFlip
      - function: ToPILImage
        params:
          mode: RGB
      - function: CenterCrop
        params:
          size: 224
      - function: ToTensor
      - function: Normalize
        params:
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225

train:
  condition:
    epoch: 10
    early_stopping_rounds: 10
    verbose: 1
    seed: 1116
  model:
    name: resnet50
    pretrained: True
  optimizer:
    algorithm: Adam
    params:
      lr: 0.001
  scheduler:
    algorithm: StepLR
    params:
      step_size: 10
  criterion:
    algorithm: CrossEntropyLoss

inference:
  null
