summary:
  task: regression
  fold: 1
  csv: expand_train

dataloader:
  dataset: benedge
  batch_size: 32
  eval_batch_size: 4
  preprocess: null
  transform:
    train:
      - function: RandomRotation
        params:
          degrees: 180
      - function: RandomHorizontalFlip
      - function: Resize
        params:
          size: 256
      - function: ToTensor
      - function: Normalize
        params:
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
    valid:
      - function: RandomRotation
        params:
          degrees: 180
      - function: RandomHorizontalFlip
      - function: Resize
        params:
          size: 256
      - function: ToTensor
      - function: Normalize
        params:
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225
    test:
      - function: RandomRotation
        params:
          degrees: 180
      - function: RandomHorizontalFlip
      - function: Resize
        params:
          size: 256
      - function: ToTensor
      - function: Normalize
        params:
          mean:
            - 0.485
            - 0.456
            - 0.406
          std:
            - 0.229
            - 0.224
            - 0.225

train:
  condition:
    epoch: 150
    early_stopping_rounds: 10
    verbose: 1
    seed: 1116
  model:
    name: efficientnet_b4
    pretrained: True
  optimizer:
    algorithm: Adam
    params:
      lr: 0.001
      weight_decay: 0.00001
  scheduler:
    algorithm: StepLR
    params:
      step_size: 5
      gamma: 0.1
  criterion:
    algorithm: MSELoss

inference:
  null
